// import { Inter }  from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import Header from "@/components/header";
// import { Toaster } from "sonner";

// const inter=Inter({subsets:['latin']})
// export const metadata = {
//   title: "finance tracker",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//      <ClerkProvider>
//     <html lang="en">
//       <body
//         className={`${inter.className}`}
//       >
//         <Header/>
//         <main className="min-h-screen"> {children}</main>
//         <Toaster richColors/>
//          <footer className="bg-blue-200 py-12">
//           <div className="container font-bold mx-auto px-4 text-center text-black">
//             <p className="animate-bounce">SpendAI❤️</p>
//           </div>
//          </footer>
//       </body>
//     </html>
  
//      </ClerkProvider>
// );
// }



import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes"; 
import { Switch } from "@/components/ui/switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spend AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning> 
        <body
          className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:text-white transition-colors duration-300`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            <footer className="bg-blue-200 dark:bg-gray-800 py-12 transition-all duration-300">
              <div className="container font-bold mx-auto px-4 text-center text-black dark:text-white">
                <p className="animate-bounce">SpendAI❤️</p>
                <Switch>
                  
                </Switch>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
